version: '3'

services:
  dbtwo:
    restart: always
    image: postgres:10
    ports:
    - "5435:5432"
    volumes:
    - ./data:/var/lib/postgresql/data
#  web:
#    restart: "no"
#    build: .
#    command: python3 manage.py runserver 0.0.0.0:8030
#    volumes:
#      - .:/code
#    ports:
#      - "8030:8030"
#    depends_on:
#      - dbtwo
#    links:
#      - dbtwo
volumes:
  dbtwo:
