# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, choices=[('zarplata', 'Зарплата'), ('gift', 'Подарки'), ('other', 'Другое')], help_text='Выберите категорию дохода', max_length=120, null=True)),
            ],
        ),
    ]
