# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profit',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profit',
            name='category',
            field=models.CharField(blank=True, choices=[('zarplata', 'Зарплата'), ('gift', 'Подарки'), ('other', 'Другое')], default='zarplata', help_text='Выберите категорию дохода', max_length=120, null=True),
        ),
    ]
