# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0004_remove_profit_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
