# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0006_auto_20171112_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
