# Generated by Django 2.0.8 on 2018-09-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_20180920_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
