# Generated by Django 2.2 on 2019-07-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='auto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.Auto'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(help_text='Действие', max_length=200),
        ),
    ]
