# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeexpend',
            name='kolvo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='financeexpend',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
