# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20170814_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeexpend',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
