# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20170814_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeexpend',
            name='timestamp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='financeexpend',
            name='updated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
