# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20170814_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeexpend',
            name='kolvo',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
