# Generated by Django 2.0 on 2018-01-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20171202_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeexpend',
            name='category',
            field=models.CharField(blank=True, choices=[('auto', 'Авто'), ('products', 'Продукты'), ('repairs', 'Ремонт'), ('health', 'Здоровье/Аптека'), ('home', 'Предметы в дом'), ('sortir', 'Бытовая химия/расходные'), ('learn', 'Обучение'), ('relax', 'Отдых / Развлечения'), ('other', 'Прочее'), ('mobile', 'Связь / Интернет')], help_text='Выберите категорию', max_length=120, null=True),
        ),
    ]
