# Generated by Django 2.0 on 2018-01-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20180119_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeexpend',
            name='files',
            field=models.ImageField(null=True, upload_to='files/'),
        ),
    ]
