# Generated by Django 2.0 on 2018-01-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_financeexpend_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeexpend',
            name='files',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
