# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20180119_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeexpend',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
