# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20180219_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, choices=[('zarplata', 'Зарплата'), ('card', 'На карту'), ('gift', 'Подарки'), ('other', 'Другое')], default='zarplata', help_text='Выберите категорию дохода', max_length=120, null=True)),
                ('timestamp', models.DateField()),
                ('updated', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
    ]
