# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_profit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profit',
            new_name='FinanceProfit',
        ),
    ]
