# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-08 20:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_financeplane'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeplane',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='financeplane',
            name='updated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financeplane',
            name='description',
            field=models.CharField(help_text='Описание', max_length=500),
        ),
    ]
