# Generated by Django 2.0.8 on 2018-09-20 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_financeexpend_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeexpend',
            name='auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.Auto'),
        ),
    ]
