# Generated by Django 2.1.2 on 2018-10-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_advert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeexpend',
            options={'verbose_name': 'Строка расхода', 'verbose_name_plural': 'Расходы'},
        ),
    ]
