# Generated by Django 2.2 on 2019-07-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_auto_20181028_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeexpend',
            name='category',
            field=models.CharField(blank=True, choices=[('auto', 'Авто'), ('products', 'Продукты'), ('repairs', 'Ремонт'), ('health', 'Здоровье/Аптека'), ('home', 'Предметы в дом'), ('sortir', 'Бытовая химия/расходные'), ('learn', 'Обучение'), ('relax', 'Отдых / Развлечения'), ('mobile', 'Связь / Интернет'), ('clothes', 'Одежда / Обувь'), ('other', 'Прочее')], help_text='Выберите категорию', max_length=120, null=True),
        ),
    ]
